# Generated by Django 4.2.4 on 2023-10-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catergory_name',
            new_name='category_name',
        ),
    ]
