# Generated by Django 4.2.4 on 2024-02-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
